export const TableNames = [
  "Attachment",
  "AttachmentGroup",
  "HetekaData",
  "MemberOfParliament",
  "PrimaryKeys",
  "SaliDBAanestys",
  "SaliDBAanestysAsiakirja",
  "SaliDBAanestysEdustaja",
  "SaliDBAanestysJakauma",
  "SaliDBAanestysKieli",
  "SaliDBIstunto",
  "SaliDBKohta",
  "SaliDBKohtaAanestys",
  "SaliDBKohtaAsiakirja",
  "SaliDBMessageLog",
  "SaliDBPuheenvuoro",
  "SaliDBTiedote",
  "SeatingOfParliament",
  "VaskiData",
] as const;
