version: "3.8"

services:
  postgres:
    image: postgres:17-alpine
    container_name: avoimempi-eduskunta-postgres
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - avoimempi-eduskunta-network-db
    restart: always

  flyway:
    image: flyway/flyway:11-alpine
    container_name: avoimempi-eduskunta-flyway
    command: "-url=jdbc:postgresql://postgres:5432/$POSTGRES_DB -user=$POSTGRES_USER -password=$POSTGRES_PASSWORD -locations=filesystem:/migrations migrate"
    env_file:
      - .env
    volumes:
      - ./migrations:/migrations
    depends_on:
      - postgres
    networks:
      - avoimempi-eduskunta-network-db
    restart: "no"

  server:
    build:
      context: ./
      dockerfile: ./modules/backend/Dockerfile
    container_name: avoimempi-eduskunta-server
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    networks:
      - avoimempi-eduskunta-network-db
    restart: always

volumes:
  postgres_data:

networks:
  avoimempi-eduskunta-network-db:
    driver: bridge
