CREATE TABLE Document (
  id INTEGER PRIMARY KEY,
  type_slug TEXT NOT NULL,
  type_name_fi TEXT,
  root_family TEXT,
  eduskunta_tunnus TEXT,
  document_type_code TEXT,
  document_number_text TEXT,
  parliamentary_year_text TEXT,
  title TEXT,
  alternative_title TEXT,
  status_text TEXT,
  language_code TEXT,
  publicity_code TEXT,
  created_at TEXT,
  laadinta_pvm TEXT,
  source_identifiointi_tunnus TEXT,
  source_muu_tunnus TEXT,
  primary_task_code TEXT,
  structure_schema_name TEXT,
  message_type TEXT,
  message_id TEXT,
  message_created_at TEXT,
  transfer_code TEXT,
  organization_slug TEXT,
  organization_name TEXT,
  meeting_slug TEXT,
  source_path TEXT
);

CREATE INDEX idx_document_type_slug ON Document(type_slug);
CREATE INDEX idx_document_tunnus ON Document(eduskunta_tunnus);
CREATE INDEX idx_document_type_code ON Document(document_type_code);

CREATE TABLE DocumentActor (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  role_code TEXT,
  person_id INTEGER,
  first_name TEXT,
  last_name TEXT,
  position_text TEXT,
  organization_text TEXT,
  extra_text TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id),
  FOREIGN KEY (person_id) REFERENCES Representative(person_id)
);

CREATE TABLE DocumentSubject (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  subject_text TEXT NOT NULL,
  subject_uri TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocumentAttachment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  native_id TEXT,
  use_type TEXT,
  file_name TEXT,
  file_path TEXT,
  format_name TEXT,
  format_version TEXT,
  hash_algorithm TEXT,
  hash_value TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocumentRelation (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  relation_type TEXT NOT NULL,
  target_tunnus TEXT,
  target_system TEXT,
  source_field TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE CommitteeSession (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  committee_code TEXT NOT NULL,
  session_key TEXT UNIQUE,
  document_id INTEGER,
  label TEXT,
  number_text TEXT,
  parliamentary_year_text TEXT,
  start_time TEXT,
  end_time TEXT,
  source_path TEXT,
  FOREIGN KEY (committee_code) REFERENCES Committee(code),
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

ALTER TABLE Session ADD COLUMN roll_call_document_id INTEGER;
ALTER TABLE Session ADD COLUMN agenda_document_id INTEGER;
ALTER TABLE Session ADD COLUMN minutes_document_id INTEGER;

ALTER TABLE Section ADD COLUMN source_section_id INTEGER;
ALTER TABLE Section ADD COLUMN source_parent_section_id INTEGER;
ALTER TABLE Section ADD COLUMN document_id INTEGER;
ALTER TABLE Section ADD COLUMN document_tunnus TEXT;

CREATE TABLE SessionMinutesItem (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_key TEXT NOT NULL,
  minutes_document_id INTEGER NOT NULL,
  item_type TEXT NOT NULL,
  ordinal INTEGER,
  title TEXT,
  identifier_text TEXT,
  processing_title TEXT,
  note TEXT,
  source_item_id INTEGER,
  source_parent_item_id INTEGER,
  FOREIGN KEY (session_key) REFERENCES Session(key),
  FOREIGN KEY (minutes_document_id) REFERENCES Document(id)
);

CREATE INDEX idx_minutes_item_session ON SessionMinutesItem(session_key);
CREATE INDEX idx_minutes_item_source_item ON SessionMinutesItem(source_item_id);

CREATE TABLE SessionMinutesAttachment (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_key TEXT NOT NULL,
  minutes_document_id INTEGER NOT NULL,
  minutes_item_id INTEGER,
  title TEXT,
  related_document_tunnus TEXT,
  file_name TEXT,
  file_path TEXT,
  native_id TEXT,
  FOREIGN KEY (session_key) REFERENCES Session(key),
  FOREIGN KEY (minutes_document_id) REFERENCES Document(id),
  FOREIGN KEY (minutes_item_id) REFERENCES SessionMinutesItem(id)
);

CREATE TABLE SessionSectionSpeech (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  session_key TEXT NOT NULL,
  section_key TEXT NOT NULL,
  minutes_item_id INTEGER,
  source_document_id INTEGER,
  section_ordinal INTEGER,
  speech_ordinal INTEGER,
  person_id INTEGER,
  first_name TEXT,
  last_name TEXT,
  party TEXT,
  position TEXT,
  speech_type TEXT,
  start_time TEXT,
  end_time TEXT,
  content TEXT,
  link_key TEXT,
  source_item_id INTEGER,
  source_path TEXT,
  FOREIGN KEY (session_key) REFERENCES Session(key),
  FOREIGN KEY (section_key) REFERENCES Section(key),
  FOREIGN KEY (minutes_item_id) REFERENCES SessionMinutesItem(id),
  FOREIGN KEY (source_document_id) REFERENCES Document(id),
  FOREIGN KEY (person_id) REFERENCES Representative(person_id)
);

CREATE INDEX idx_sss_session_section ON SessionSectionSpeech(session_key, section_key);
CREATE INDEX idx_sss_person ON SessionSectionSpeech(person_id);
CREATE INDEX idx_sss_start_time ON SessionSectionSpeech(start_time);
CREATE INDEX idx_sss_link_key ON SessionSectionSpeech(link_key);

CREATE TABLE DocumentSectionEvent (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  document_id INTEGER NOT NULL,
  section_key TEXT,
  event_ordinal INTEGER,
  event_date TEXT,
  phase_code TEXT,
  phase_title TEXT,
  action_code TEXT,
  action_text TEXT,
  actor_summary TEXT,
  source_field TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id),
  FOREIGN KEY (section_key) REFERENCES Section(key)
);

CREATE TABLE DocType_asialista (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_asiantuntijalausunnon_liite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_asiantuntijalausunto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_asiantuntijasuunnitelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_asiat_joiden_kasittely_on_paattynyt_valtiopaivilla_xxxx (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_asioiden_maara_vaalikausittain (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_budjetin_alikohta (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eduskunnan_kirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eduskunnan_vastaus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eduskunnassa_vvvv_valtiopaivilla_kasittelyssa_olevat_asiat (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eduskuntatyon_jarjestaminen (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_erikoisvaliokunnissa_kasiteltavina_olevat_taysistuntoasiat_ja_niiden_valmistumisarviot (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_erikoisvaliokunnissa_kasiteltavana_olevat_eu_asiat (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_erikoisvaliokuntien_antamat_lausunnot_ja_kannanotot_u_e_ja_utp_asioista_vaalikaudella (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_esityslista (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eun_asiakirjaluonnos (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eun_raportti (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_eurooppa_neuvoston_ja_eun_neuvostojen_kokoukset (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_hakemisto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_hallituksen_esitys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_ilmoitus_asiantuntijalle (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_istuntosuunnitelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kannanotto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kansalaisaloite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kertomus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_keskustelualoite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kirjallinen_kysymys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kirjelma_saadoskokoelmaan (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_kokoussuunnitelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_lakialoite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_lausuma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_lepaamaan_hyvaksytty_lakiehdotus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_liiteasiakirja (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_lisaselvitys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_lisatalousarvioaloite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_ministerien_sidonnaisuudet (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_ministerion_selvitys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_muu_asia (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_muu_asiakirja (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_nimenhuutoraportti (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_peruuttamisilmoitus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_peruutuskirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_puhemiesneuvoston_ehdotus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_paivajarjestys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_paaministerin_ilmoitus (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_poytakirja (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_poytakirjan_asiakohta (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_poytakirjan_liite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_poytakirjan_muu_asiakohta (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_suullinen_kysymys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_suv_asialista (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_talousarvioaloite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_tilastotietoja_valiokunnista_valtiopaivilla_xxxx (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_toimenpidealoite (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_toissijaisuusasia (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_toissijaisuusasioiden_lista (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_taysistunnon_poytakirjan_paasivu (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_taysistunnon_poytakirjat (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_unknown (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vaali (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vahvistamatta_jaanyt_laki (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valiokunnan_lausunto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valiokunnan_mietinto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valiokunnan_oma_asia (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valiokunnissa_kasiteltavina_olevat_taysistuntoasiat (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valiokuntien_poytakirjat (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvostolta_saapuneet_u_asiat_ministerioittain_vaalikaudella_xxxx_yyyy (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_e_jatkokirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_e_selvitys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_kirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_selonteko (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_tiedonanto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_u_jatkokirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_u_kirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_utp_jatkokirjelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valtioneuvoston_utp_selvitys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vapautuspyynto (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vastaus_kirjalliseen_kysymykseen (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vastaus_saadoskokoelmaan (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_vastine (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_viikkosuunnitelma (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);

CREATE TABLE DocType_valikysymys (
  document_id INTEGER PRIMARY KEY,
  title_text TEXT,
  subtitle_text TEXT,
  summary_text TEXT,
  content_text TEXT,
  question_text TEXT,
  answer_text TEXT,
  decision_text TEXT,
  statement_text TEXT,
  justification_text TEXT,
  proposal_text TEXT,
  statute_text TEXT,
  signing_text TEXT,
  note_text TEXT,
  meeting_start TEXT,
  meeting_end TEXT,
  agenda_state TEXT,
  related_document_tunnus TEXT,
  FOREIGN KEY (document_id) REFERENCES Document(id)
);
