services:
  workspace:
    image: mcr.microsoft.com/devcontainers/typescript-node:22
    init: true
    command: sleep infinity
    volumes:
      - ..:/workspaces/avoimempi-eduskunta:Z
      - node_modules:/workspaces/avoimempi-eduskunta/node_modules
    env_file:
      - ./.env.devcontainer

  elasticmq:
    image: docker.io/softwaremill/elasticmq-native:1.6.16
    restart: unless-stopped
    ports:
      - "9324:9324"

volumes:
  node_modules:
