CREATE TABLE Section (
  id INTEGER PRIMARY KEY,
  key TEXT UNIQUE,
  identifier TEXT,
  title TEXT,
  ordinal INTEGER,
  note TEXT,
  processing_title TEXT,
  resolution TEXT,
  session_key TEXT,
  agenda_key TEXT,
  modified_datetime TEXT,
  vaski_id INTEGER,
  FOREIGN KEY (session_key) REFERENCES Session(id),
  FOREIGN KEY (agenda_key) REFERENCES Agenda(key)
);

CREATE TABLE Voting (
  id INTEGER PRIMARY KEY,
  number INTEGER UNIQUE,
  start_time TEXT,
  annulled INTEGER,
  title TEXT,
  proceedings_name TEXT,
  proceedings_url TEXT,
  result_url TEXT,
  n_yes INTEGER,
  n_no INTEGER,
  n_abstain INTEGER,
  n_absent INTEGER,
  n_total INTEGER,
  section_processing_phase TEXT,
  session_number INTEGER,
  session_key TEXT,
  modified_datetime TEXT,
  section_id INTEGER,
  section_key TEXT,
  main_section_id TEXT,
  FOREIGN KEY (session_number) REFERENCES Session(number),
  FOREIGN KEY (session_key) REFERENCES Session(key),
  FOREIGN KEY (section_id) REFERENCES Section(id),
  FOREIGN KEY (section_key) REFERENCES Section(key),
  FOREIGN KEY (main_section_id) REFERENCES Section(id)
);