import { Database } from "bun:sqlite";
import fs from "node:fs";
import path from "node:path";
import { getDatabasePath } from "../packages/shared/database";

const hrefs = [
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Aalto_Touko_web_7152.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ahde_Matti_web_103.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ahonen_Esko_web_804.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ahvenj%C3%A4rvi_Sauli_web_1086.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Akaan-Penttil%C3%A4_Eero_web_558.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ala_Nissila_Olavi_web_7092.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Alanko-Kahiluoto-Outi-web-v7158-914.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Alatalo_Mikko_web_7100.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Andersson_Claes_web_121.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Andersson_Janina_web_446.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Andersson-Li-web-1310.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Anttila%20Sirkka-Liisa_web_6895.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Arhinmaki-Paavo-web-v7598-917.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Asko-Seljavaara_Sirpa_web_764.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Autio_Risto_web_966.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Backman_Jouni_web_133.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Berner_Anne_web_6462.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Blomqvist-Thomas-web-v7897-923.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Brax_Tuija_web_448.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Donner_J%C3%B6rn_web_109.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Elo_Simon_web_7396.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Elovaara_Tiina_web_7355.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Feldt_Ranta_Maarit_web_7194.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Forsius_Merikukka_web_560.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Gestrin_Christina_web_623.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Gustafsson-Jukka-web-v7715-116.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Guzenina-Maria-web-926.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/G%C3%A4stgivars_Lars_web_1103.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Haapanen_Satu_web_1104.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Haapoja_Susanna_web_806.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Haglund_Carl_web2_6782.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hakanen_Pertti_web_6774.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hakkarainen-Teuvo-web-v6860-1107.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hakola_Juha_web_916.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Halmeenpaa_Hanna_web_7163.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Harkimo_Leena_web_562.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hassi-Satu-web-v7696-363.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hautala_Heidi_web_352.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hautala_Lasse_web_6687.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Heikkil%C3%A4_Lauri_web_1115.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Heikkinen-Hannakaisa-web-v8270-938.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Heinaluoma_Eero_web_7486.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hemmil%C3%A4_Pertti_web_563.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hemming_Hanna-Leena_web_777.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Henriksson-Anna-Maja-web-941.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hiltunen_Rakel_web_564.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hirvisaari_James_web_1117.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Holmlund_Anne_web_630.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Holopainen-Mari-web-v1581-1386.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hongisto_Reijo_web_7087.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Huovinen_Susanna_web_7055.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hurskainen_Sinikka_web_136.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hyss%C3%A4l%C3%A4_Liisa_web_455.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/H%C3%A4k%C3%A4mies_Jyri_web_566.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Hanninen-Katja-web-v7706-1276.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/H%C3%A4nninen_Tuomo_web_799.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ihalainen_Lauri_web_6565.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Immonen-Olli-web-v7393-1122.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jaakonsaari_Liisa_web_147.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jalonen_Ari_web_7381.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jarva_Marisanna_web_7418.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jaskari_Harri_web_6963.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jokinen-Kalle-web-v7995-1056.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Joutsenlahti_Anssi_web_910615.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Juhantalo_Kauko_web_6868.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jungner_Mikael_web_1125.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jurva_Johanna_web_1127.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Juurikkala_Timo_web_1053.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Jarvinen-Heli-web-v1527-930.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/J%C3%A4%C3%A4skel%C3%A4inen_Jouko_web_405.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/J%C3%A4%C3%A4skel%C3%A4inen_Pietari_web_1052.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kalli_Timo_web_7504.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kallio_Reijo_web_459.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kalliom%C3%A4ki_Antti_web_166.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kalliorinne-Risto-web-1132.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kallis_Bjarne_web_417.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kaltiokumpu_Oiva_web_964.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kanerva-Ilkka-web-v8029-170.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kangas_Matti_web_614.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kankaanniemi_Toimi_web-v0747-175.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kantola_Ilkka_web_6922.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karhu_Saara_web_568.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karhuvaara_Arja_web_918.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kari-Emma-web-v7100-1336.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karimaki_Johanna_web_7320.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karjula_Ky%C3%B6sti_web_462.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karpela_Tanja_web_569.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karvo_Ulla_web_969.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kasvi_Jyrki_web_7027.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Katainen_Elsi_web_6942.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Katainen_Jyrki_web_571.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kataja_Sampsa_web_958.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kaunisto_Timo_web_950.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kauppila_Matti_web_781.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kautto-Juho-web-v7334-1444.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kerola_Inkeri_web_613.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Keranen_Niilo_web_6531.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kettunen_Pentti_web_306.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kiljunen-Anneli-web-v8182-791.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kinnunen-Jari-web-v5360-1480.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kinnunen-Mikko-web-v6707-1453.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kivela_Kimmo_web_6779.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kiviniemi_Mari_web_465.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kiviranta-Esko-web-v8054-779.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kivisaari-Pasi-web-v6729-1442.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kokko_Osmo_web_1140.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Komi_Katri_web_574.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koponen-Noora-web-v5744-1404.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Korhonen_Martti_web_386.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Korhonen_Timo_web_6952.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Korkeaoja_Juha_web_403.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koskela_Laila_web_1143.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koski_Susanna_web_6652.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koski_Valto_web_469.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koskinen_Jari_web_532.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Koskinen_Marjaana_web_471.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kotiaho-Jouni-web-v6885-1448.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kuisma_Risto_web_473.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kulmala_Kari_web_6753.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kulmuni-Katri-web-1340.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kumpula-Natri-Miapetra-web-807.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kuoppa_Mikko_web_444.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kurvinen_Esko_web_576.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kuusisto_Merja_web_927.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kyllonen-Merja-web-963.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/K%C3%A4hk%C3%B6nen_Lauri_web_577.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/K%C3%A4rkk%C3%A4inen_Kari_web_578.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/K%C3%A4rn%C3%A4_Jukka_web_1145.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Karna-Mikko-web-v6604-1348.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kaariainen_Seppo_web_6560.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Kontta-Joonas-web-v6927-1446.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laakso_Jaakko_web_407.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lahtela_Esa_web_478.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laitinen_Reijo_web_370.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laitinen_Pesola_Jaana_web2_6871.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lapintie_Annika_web_7430.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Larikka_Jari_web_924.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laukkanen-Antero-web-v6584-1343.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laukkanen_Markku_web_376.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lauslahti_Sanna_web7550.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Laxell_Jouko_web_847.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lehti_Eero_kok.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lehto-Rami-web-v6756-1344.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lehtomaki_Paula_web.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Leppa-Jari-web-v7179-582.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lind%C3%A9n_Suvi_web_480.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lindstrom_Jari_web_6457.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lipponen_P%C3%A4ivi_web_915.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lohela_Maria_web_6995.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Lohikoski-Pia-web-v8359-1399.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Louhelainen_Anne_web_6679.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Maijala_Eeva_Maria_web_7609.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Manninen_Hannes_web_483.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Marin-Sanna-web-1297.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Matikainen-Kallst%C3%B6m_Marjo_web_775.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Mattila_Pirkko_web_7464.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Mieto_Juha_web_944.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Modig_Silvia_web_6877.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Mustajarvi-Markus-web-v6810-802.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Mykkanen-Kai-web-1300.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Myller_Riitta_web_7445.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Myllykoski-Jari-web-v8061-1154.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/M%C3%A4kel%C3%A4_Jukka_web_937.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Makela_Outi_web_7453.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/M%C3%A4kinen_Tapani_web_817.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/M%C3%A4kip%C3%A4%C3%A4_Lea_web_2981.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Makisalo-Ropponen-Merja-web-v6908-1087.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Makynen-Jukka-web-v6663-1438.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/M%C3%A4nnist%C3%B6_Lasse_web_1156.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Mantyla_Hanna_web_7683.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/M%C3%A4ntymaa_Markku_web_1090.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Molsa_Martti_web_7353.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Naucler_Elisabeth_web_973.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nepponen_Olli_web_585.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Niikko-Mika-web-v7871-1092.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Niinisto_Jussi_web_7023.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Niinist%C3%B6_Sauli_web_223.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Niinisto_Ville_web_7329.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nivala_Eija_web_4048.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nordman_H%C3%A5kan_web_224.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nurmi_Tuija_web_486.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nurminen-Ilmari-web-1302.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nylander_Mikaela_web_7126.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Nylund_Mats_web_7625.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ohisalo-Maria-web-1387.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Oinonen_Lauri_web_587.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Oinonen_Pentti_web_6722.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ojansuu-Kaunisto_Kirsi_web_588.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ollila_Heikki_A_web_204.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Paajanen_Reijo_web_789.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Paasio_Heli_web_589.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Paatero-Sirpa-web-v8230-887.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Packalen-Tom-web-v7423-1095.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pakkanen_Markku_web_7294.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Palm_Sari_web_922.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Palola_Mikael_web_1277.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Paloniemi_Aila_web_2044.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Parviainen_Olli_Poika_web_7476.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Parviainen_Ulla_web_6479.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pekkarinen_Mauri_web_7474.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pelkonen-Jaana-web-v7353-1098.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Peltokorpi_Terhi_web_848.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Peltonen-Eemeli-web-1496.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Peltonen_Tuula_web_955.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pentti_Klaus_web_785.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Perkio-Sanna-web-919.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Petelius-Pirkka-Pekka-web-v7525-1405.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pihlajaniemi_Petri_web_951.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Piirainen-Raimo-web-v7927-1051.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pirttilahti-Arto-web-v7217-1101.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Puhjo_Veijo_web_495.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pulliainen_Erkki_web_240.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Puska_Pekka_web_4927.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Puumala_Tuomo_web_7298.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Pylvas-Juha-web-v7045-1305.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Raassina_Sari_web_7239.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Raatikainen-Mika-web-v7906-1275.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rajala_Lyly_web_801.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rajam%C3%A4ki_Kari_web_228.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rantakangas-Antti-web-v7562-592.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rauhala_Leena_web_593.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ravi_Pekka_web_594.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rehn_Olli_web_7185.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rehn-Kivi-Veronica-web-v7238-1374.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rehula_Juha_web2_7437.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Reijonen_Eero_web7148.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rinne-Antti-web-v7738-1274.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rossi_Markku_web_7071.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Rundgren_Simo_web_803.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ruoho_Veera_web_6918.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ruohonen-Lerner_Pirkko_web_920.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/R%C3%B6nni_Tero_web_595.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Saarakkala_Vesa_Matti_web_7717.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Saarikko-Annika-web-1157.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Saarinen_Matti_web_253.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Said-Ahmed-Suldaan-web-v5022-1479.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salla-Aura-web-1487.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salo_Mauri_web_515.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salo_Petri_web_596.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salolainen_Pertti_web_6842.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salonen-Kristiina-web-v7940-1102.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Salovaara_Pertti_web_762.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sankelo-Janne-web-v7407-1105.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Saramo-Jussi-web-1400.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sasi_Kimmo_web_261.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Semi-Matti-web-v7319-1315.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Seuruj%C3%A4rvi_Janne_web_965.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sihto_Paula_web_949.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sinnem%C3%A4ki_Anni_web_600.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sipila-Juha-web-v8346-1108.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sirn%C3%B6_Minna_web_788.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sjoblom-Ruut-web-v7842-1395.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Skinnari_Jouko_web_267.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Slunga-Poutsalo-Riikka-web-v6591-1393.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Soini_Timo_web_7235.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Soinikoski-Mirka-web-v7505-1416.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Soininvaara_Osmo_web_265.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Soukola_Ismo_web_1110.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Stubb_Alexander_web_7460.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Sumuvuori_Johanna_web_894.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Suomela-Iiris-web-v7058-1423.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Suutari_Eero_web_7392.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/S%C3%A4rkiniemi_Seppo_web_773.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/S%C3%B6derman_Jakob_web_311.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Taavitsainen_Satu_web_6817.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Taberman_Tommy_web_929.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/al-Taee-Hussein-web-v7834-1397.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Taimela-Katja-web-v7890-952.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tainio_Hanna_web_1112.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Taiveaho_Satu_web_782.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Talja_Martti_web_7007.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tallqvist_Tarja_web_933.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tennil%C3%A4_Esko-Juhani_web_278.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Terho_Sampo_web_6822.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Thors_Astrid_web_770.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tiainen_Eila_web_1113.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tiilikainen_Kimmo_web_7613.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tiura-Marja-web-602.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tiusanen_Pentti_web_505.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Toivakka_Lenita_web_7074.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Toivola_Jani_web_7341.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tolppanen_Maria_web_6493.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tolvanen-Kari-web-v7852-1118.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Torniainen-Ari-web-v7141-1120.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Torsti_Pilvi_web_8932.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Torvinen_%20Matti_web_3845.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tossavainen_Reijo_web_1123.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Toveri-Pekka-web-1494.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tuomioja-Erkki-web-v7682-357.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Turtiainen-Ano-web-v0279-1427.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Turunen_Kaj_web.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tuupainen_Kauko_web_1130.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tynkkynen-Sebastian-web-1451.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Tolli_Tapani_web_7644.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Ukkola_Tuulikki_web_389.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Uotila_Kari_web_7659.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Urpalainen_Anu_web_1226.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Urpilainen-Jutta-web-v7863-808.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Uusipaavalniemi_Markku_web_942.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vahasalo_Raija_web_0630.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Wallin_Harry_web_7035.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Wallin_Stefan_web_7258.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vallin-Veikko-web-v6801-1420.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Valpas_Unto_web_604.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vanhanen-Matti-web-v7828-414.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vapaavuori_Jan_web_766.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vartia_Antero_web_6861.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vartiainen-Juhana-web-v7327-1330.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vehkapera_Mirja_web_7307.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vehvilainen-Anu-web-v8263-508.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Wideroos_Ulla-Maj_web_475.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Wihonen-Jussi-web-v6580-1436.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Viitamies_Pauliina_web_928.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Viljanen-Heidi-web-v7713-1414.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Viljanen_Ilkka_web_968.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vilkuna_Pekka_web_607.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Viren_Lasse_web_608.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Virkkunen_Henna_web_957.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Virolainen-Anne-Mari-web-v8007-948.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Virtanen_Erkki_web_793.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Virtanen_Pertti_web_512.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vistbacka_Raimo_web_295.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vuolanne_Antti_web_961.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Vayrynen_Paavo_web_4177.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/V%C3%A4%C3%A4t%C3%A4inen_Juha_web_1139.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Yanar_Ozan_web_6883.jpg",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Yrttiaho-Johannes-web-v7543-1407.JPG",
  "https://www.eduskunta.fi/FI/kansanedustajat/Edustajakuvat1907/Yrttiaho_Jyrki_web_945.jpg",
];

const TARGET_DIR = path.resolve(
  import.meta.dir,
  "../data/raw/OldParliamentImages",
);
if (!fs.existsSync(TARGET_DIR)) fs.mkdirSync(TARGET_DIR, { recursive: true });

const db = (() => {
  const databasePath = getDatabasePath();
  return new Database(databasePath, {
    create: true,
    readonly: true,
  });
})();

const fetchPersonId = (firstName: string, lastName: string) => {
  const stmt = db.prepare<
    { person_id: string },
    { $firstName: string; $lastName: string }
  >(
    "SELECT person_id FROM Representative WHERE TRIM(first_name) = $firstName AND TRIM(last_name) = $lastName COLLATE NOCASE",
  );
  const data = stmt.all({ $firstName: firstName, $lastName: lastName });
  stmt.finalize();
  if (data.length !== 1) {
    throw new Error(
      `Failed to find person ${firstName} ${lastName} in database`,
    );
  }
  return data[0].person_id;
};

for (const href of hrefs) {
  let personId: string | undefined;
  const fileName = decodeURIComponent(href.split("/").reverse()[0]);
  const { firstName, lastName } =
    /^(?<lastName>[A-zÄäÖöÅå-]+)_(?<firstName>[A-zÄäÖöÅå-]+)_[A-z]/i.exec(
      fileName,
    )?.groups ?? {};
  if (!firstName || !lastName) throw new Error(`Failed to match ${fileName}`);
  console.log("Trying to lookup", firstName, lastName);
  const lookup = (() => {
    switch (`${firstName} ${lastName}`) {
      case "Paula Lehtomaki":
        return fetchPersonId("Paula", "Lehtomäki");
      case "Olavi Ala_Nissila":
        return fetchPersonId("Olavi", "Ala-Nissilä");
      default:
        return fetchPersonId(firstName, lastName);
    }
  })();
  if (lookup) personId = lookup;
  if (!personId) {
    throw new Error(`Failed to retrieve person ID for ${fileName}`);
  }
  console.log(personId);
  const personRow = db
    .prepare("SELECT person_id FROM Representative WHERE person_id = $personId")
    .all({ $personId: personId });
  if (personRow.length !== 1)
    throw new Error(`Failed to match ${fileName} to ID ${personId}`);
}
