import fs from "node:fs";
import path from "node:path";

const SRC_DIR = path.join(import.meta.dirname, "../src");
const FEATURES_DIR = path.join(SRC_DIR, "features");
const OUT_FILE = path.join(SRC_DIR, "database/sql-registry.generated.ts");

function walkFiles(dir: string): string[] {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? walkFiles(fullPath) : [fullPath];
  });
}

const sqlFiles = walkFiles(FEATURES_DIR)
  .filter((filePath) => filePath.endsWith(".sql"))
  .sort();

const seen = new Set<string>();
const imports: string[] = [];
const entries: string[] = [];

for (const [index, filePath] of sqlFiles.entries()) {
  const queryFile = path.basename(filePath);
  if (seen.has(queryFile)) {
    throw new Error(`Duplicate SQL filename across features: ${queryFile}`);
  }
  seen.add(queryFile);

  const varName = `sql${index}`;
  const relativePath = path.relative(path.dirname(OUT_FILE), filePath);
  const importPath = relativePath.startsWith(".")
    ? relativePath
    : `./${relativePath}`;

  imports.push(`import ${varName} from "${importPath}";`);
  entries.push(
    `  { queryFile: ${JSON.stringify(queryFile)}, filePath: ${JSON.stringify(filePath)}, sql: ${varName} },`,
  );
}

const content = `// Generated by packages/server/scripts/generate-sql-registry.ts — do not edit by hand.

${imports.join("\n")}

export interface SqlRegistryEntry {
  queryFile: string;
  filePath: string;
  sql: string;
}

export const QUERY_REGISTRY: SqlRegistryEntry[] = [
${entries.join("\n")}
];
`;

fs.writeFileSync(OUT_FILE, content);
console.log(`Generated ${path.relative(process.cwd(), OUT_FILE)} (${sqlFiles.length} SQL files)`);
