export const sql = String.raw;

// Future query ideas (not implemented yet):
// 1) Session-level document timeline (agenda -> minutes -> attachments by creation time)
// 2) Committee session feed with linked documents and participant stats
// 3) Speaker-level document references (which documents each speech explicitly discussed)
// 4) Document relation graph traversal (multi-hop links from HE -> committee docs -> votes)
// 5) Per-document full-text search over normalized document/event tables

export { default as ageDivisionOverTime } from "./queries/AGE_DIVISION_OVER_TIME.sql";
export { default as closeVotes } from "./queries/CLOSE_VOTES.sql";
export { default as coalitionVsOpposition } from "./queries/COALITION_VS_OPPOSITION.sql";
export { default as committeeOverview } from "./queries/COMMITTEE_OVERVIEW.sql";
export { default as currentComposition } from "./queries/CURRENT_COMPOSITION.sql";
export { default as dissentTracking } from "./queries/DISSENT_TRACKING.sql";
export { default as federatedSearch } from "./queries/FEDERATED_SEARCH.sql";
export { default as genderDivisionOverTime } from "./queries/GENDER_DIVISION_OVER_TIME.sql";
export { default as governmentMemberships } from "./queries/GOVERNMENT_MEMBERSHIPS.sql";
export { default as leavingParliamentRecords } from "./queries/LEAVING_PARLIAMENT.sql";
export { default as mpActivityRanking } from "./queries/MP_ACTIVITY_RANKING.sql";
export { default as partyDiscipline } from "./queries/PARTY_DISCIPLINE.sql";
export { default as partyMembers } from "./queries/PARTY_MEMBERS.sql";
export { default as partyParticipationByGovernment } from "./queries/PARTY_PARTICIPATION_BY_GOVERNMENT.sql";
export { default as partySummary } from "./queries/PARTY_SUMMARY.sql";
export { default as personCommittees } from "./queries/PERSON_COMMITTEES.sql";
export { default as personDissents } from "./queries/PERSON_DISSENTS.sql";
export { default as personGroupMemberships } from "./queries/PERSON_GROUP_MEMBERSHIPS.sql";
export { default as personSpeeches } from "./queries/PERSON_SPEECHES.sql";
export { default as personTerms } from "./queries/PERSON_TERMS.sql";
export { default as recentActivity } from "./queries/RECENT_ACTIVITY.sql";
export { default as representativeDetails } from "./queries/REPRESENTATIVE_DETAILS.sql";
export { default as representativeDistricts } from "./queries/REPRESENTATIVE_DISTRICTS.sql";
export { default as representativesPaginated } from "./queries/REPRESENTATIVES_PAGINATED.sql";
export { default as rollCallEntries } from "./queries/ROLL_CALL_ENTRIES.sql";
export { default as sectionDocumentLinks } from "./queries/SECTION_DOCUMENT_LINKS.sql";
export { default as sectionSubSections } from "./queries/SECTION_SUBSECTIONS.sql";
export { default as sectionRollCallReport } from "./queries/SECTION_ROLL_CALL_REPORT.sql";
export { default as sectionSpeechCount } from "./queries/SECTION_SPEECH_COUNT.sql";
export { default as sectionSpeeches } from "./queries/SECTION_SPEECHES.sql";
export { default as sectionVotings } from "./queries/SECTION_VOTINGS.sql";
export { default as sessionByDate } from "./queries/SESSION_BY_DATE.sql";
export { default as sessionCount } from "./queries/SESSION_COUNT.sql";
export { default as sessionDates } from "./queries/SESSION_DATES.sql";
export { default as sessionDocuments } from "./queries/SESSION_DOCUMENTS.sql";
export { default as sessionNotices } from "./queries/SESSION_NOTICES.sql";
export { default as sessionSections } from "./queries/SESSION_SECTIONS.sql";
export { default as sessionVotingCount } from "./queries/SESSION_VOTING_COUNT.sql";
export { default as sessions } from "./queries/SESSIONS.sql";
export { default as sessionsPaginated } from "./queries/SESSIONS_PAGINATED.sql";
export { default as speechActivity } from "./queries/SPEECH_ACTIVITY.sql";
export { default as speechesByDate } from "./queries/SPEECHES_BY_DATE.sql";
export { default as trustPositions } from "./queries/TRUST_POSITIONS.sql";
export { default as votesByPerson } from "./queries/VOTES_BY_PERSON.sql";
export { default as votingById } from "./queries/VOTING_BY_ID.sql";
export { default as votingParticipation } from "./queries/VOTING_PARTICIPATION.sql";
export { default as votingParticipationByGovernment } from "./queries/VOTING_PARTICIPATION_BY_GOVERNMENT.sql";
export { default as votingsByDocument } from "./queries/VOTINGS_BY_DOCUMENT.sql";
export { default as votingsSearch } from "./queries/VOTINGS_SEARCH.sql";
export { default as interpellationsList } from "./queries/INTERPELLATIONS_LIST.sql";
export { default as interpellationsCount } from "./queries/INTERPELLATIONS_COUNT.sql";
export { default as interpellationById } from "./queries/INTERPELLATION_BY_ID.sql";
export { default as interpellationByIdentifier } from "./queries/INTERPELLATION_BY_IDENTIFIER.sql";
export { default as interpellationSigners } from "./queries/INTERPELLATION_SIGNERS.sql";
export { default as interpellationStages } from "./queries/INTERPELLATION_STAGES.sql";
export { default as interpellationSubjects } from "./queries/INTERPELLATION_SUBJECTS.sql";
export { default as interpellationYears } from "./queries/INTERPELLATION_YEARS.sql";
export { default as interpellationSessions } from "./queries/INTERPELLATION_SESSIONS.sql";
export { default as govProposalsList } from "./queries/GOV_PROPOSALS_LIST.sql";
export { default as govProposalsCount } from "./queries/GOV_PROPOSALS_COUNT.sql";
export { default as govProposalById } from "./queries/GOV_PROPOSAL_BY_ID.sql";
export { default as govProposalByIdentifier } from "./queries/GOV_PROPOSAL_BY_IDENTIFIER.sql";
export { default as govProposalSignatories } from "./queries/GOV_PROPOSAL_SIGNATORIES.sql";
export { default as govProposalStages } from "./queries/GOV_PROPOSAL_STAGES.sql";
export { default as govProposalSubjects } from "./queries/GOV_PROPOSAL_SUBJECTS.sql";
export { default as govProposalLaws } from "./queries/GOV_PROPOSAL_LAWS.sql";
export { default as govProposalYears } from "./queries/GOV_PROPOSAL_YEARS.sql";
export { default as govProposalSessions } from "./queries/GOV_PROPOSAL_SESSIONS.sql";
export { default as writtenQuestionsList } from "./queries/WRITTEN_QUESTIONS_LIST.sql";
export { default as writtenQuestionsCount } from "./queries/WRITTEN_QUESTIONS_COUNT.sql";
export { default as writtenQuestionById } from "./queries/WRITTEN_QUESTION_BY_ID.sql";
export { default as writtenQuestionByIdentifier } from "./queries/WRITTEN_QUESTION_BY_IDENTIFIER.sql";
export { default as writtenQuestionSigners } from "./queries/WRITTEN_QUESTION_SIGNERS.sql";
export { default as writtenQuestionStages } from "./queries/WRITTEN_QUESTION_STAGES.sql";
export { default as writtenQuestionSubjects } from "./queries/WRITTEN_QUESTION_SUBJECTS.sql";
export { default as writtenQuestionYears } from "./queries/WRITTEN_QUESTION_YEARS.sql";
export { default as writtenQuestionSessions } from "./queries/WRITTEN_QUESTION_SESSIONS.sql";
export { default as committeeReportsList } from "./queries/COMMITTEE_REPORTS_LIST.sql";
export { default as committeeReportsCount } from "./queries/COMMITTEE_REPORTS_COUNT.sql";
export { default as committeeReportById } from "./queries/COMMITTEE_REPORT_BY_ID.sql";
export { default as committeeReportByIdentifier } from "./queries/COMMITTEE_REPORT_BY_IDENTIFIER.sql";
export { default as committeeReportMembers } from "./queries/COMMITTEE_REPORT_MEMBERS.sql";
export { default as committeeReportExperts } from "./queries/COMMITTEE_REPORT_EXPERTS.sql";
export { default as committeeReportYears } from "./queries/COMMITTEE_REPORT_YEARS.sql";
export { default as committeeReportSessions } from "./queries/COMMITTEE_REPORT_SESSIONS.sql";
